version: '3.8'

services:
  mssql:
    container_name: mssql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: TinderPassword
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    restart: always

volumes:
  mssql-data:
